### PR TITLE
Add VEML7700 Breakout

### PR DESCRIPTION
**Pull request by dbrgn**
##### SUMMARY

Add cmp/pkg/dev for VEML7700 ambient light sensor breakout.

https://www.adafruit.com/product/4162

The breakout board provides an additional pin (3Vo) not present on the "pure" VEML7700, therefore I made a dedicated component.

The PCB:

image

Package:

2020-08-17-231758_374x427_scrot

##### OPEN QUESTIONS / UNRESOLVED ISSUES

None

##### CHECKLIST

- [x] I have read and followed the [library conventions](https://docs.librepcb.org/#libraryconventions).
- [x] For packages, I followed IPC7351C (see details in library conventions).
- [x] I'm the copyright owner of the added content (i.e. the changes are made by myself, not copied/imported from somewhere else).
- [x] I agree to publish all my changes under the [CC0 Public Domain License](https://en.wikipedia.org/wiki/CC0), allowing everyone to use and modify the content without any restrictions.

### CODE REVIEW

**Comment by ubruhin** [comment]
- The LibrePCB ICs library need to be added as a dependency (because of the generic IC symbol)
- The category of the component and device is not found on my system, where should it come from?
- Just out of curiosity, what's the purpose of the footprint without placement outline?
- I didn't review the footprint details, do you already know if everything fits as expected? :)

**Comment by dbrgn** [comment]
> The LibrePCB ICs library need to be added as a dependency (because of the generic IC symbol)

Fixed!

> The category of the component and device is not found on my system, where should it come from?

Ah, I forgot to mention, this depends on https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/pull/83.

> Just out of curiosity, what's the purpose of the footprint without placement outline?

In my case the part overlaps with multiple other footprints. This would look bad on the PCB, so I removed the silkscreen.

The overlapping is not a problem because the module is raised a bit:

image

> I didn't review the footprint details, do you already know if everything fits as expected? :)

Yes, see above!

**Comment by dbrgn** [comment]
@ubruhin any chance for a review? Your feedback was integrated, and the device was tested on real hardware.

**Comment by ubruhin** [comment]
>> The category of the component and device is not found on my system, where should it come from?
>
> Ah, I forgot to mention, this depends on https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/pull/83.

Although that PR is now merged, the category UUID of VEML7700 is still unknown (no surprise, since it is not the UUID of the category added in that PR).

**Comment by ubruhin** [comment]
@dbrgn I fixed the invalid category UUIDs by myself (assigned to "Optical Sensors"). In addition, I added a note to the description that the pkg/dev represent an old form factor (Adafruit has changed the form factor without introducing a new part number :sob:). I hope this is fine for you.

**Review by ubruhin — APPROVED** [review]

**Comment by dbrgn** [comment]
> Adafruit has changed the form factor without introducing a new part number

WTF 😕 They even add a note about it:

screenshot-20220829-021905

**Pull request merged**
